language: swift
os: osx
osx_image: xcode10.2
before_install:
  - bundle install
  - bundle update
  - bundle exec pod repo update
  - bundle exec pod update
script:
  - bundle exec fastlane ios tests
  - bundle exec fastlane mac tests
  - bundle exec fastlane tvos tests
